Repository openair-collective/Carbon-Forming, pull requests merged in 2022-10, with the labels that each got.

#16 issue/team-role
  src/views/Onboarding.vue
  src/views/teams/TeamNew.vue
Labels: bug

#26 Feature/type converters
  functions/triggers.js
  src/components/competition/CompetitionForm.vue
  src/components/project/ProjectForm.vue
  src/components/project/ProjectList.vue
  src/components/team/TeamForm.vue
  src/consts.ts
  src/modals/EnterCompetition.vue
  src/services/firestore.ts
  src/services/firestore_converters.ts
  src/store/competitions.ts
  src/store/projects.ts
  src/store/teams.ts
  src/store/user.ts
  src/types.ts
  src/views/competitions/CompetitionEdit.vue
  src/views/competitions/CompetitionShow.vue
  src/views/teams/TeamEdit.vue
  src/views/teams/TeamShow.vue
Labels: ready for review

#39 Add some more info to getting the web dev environment up...
  README.md
Labels: documentation
